### ISSUE TITLE
getRoundResults が 5 回目のバトルの後にエラーを吐く

### ISSUE THREAD

**Issue by hashi0203** [team-tissis/polylemma#136]
配列 `roundResults` の長さが 5 なのに、index 5 にアクセスしようとしてるとか？

```
Uncaught (in promise) Error: call revert exception; VM Exception while processing transaction: reverted with panic code 50 [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="getRoundResults()", data="0x4e487b710000000000000000000000000000000000000000000000000000000000000032", errorArgs=[{"type":"BigNumber","hex":"0x32"}], errorName="Panic", errorSignature="Panic(uint256)", reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)
    at Logger.makeError (index.ts:269:1)
    at Logger.throwError (index.ts:281:1)
    at Interface.decodeFunctionResult (interface.ts:427:1)
    at Contract.<anonymous> (index.ts:400:1)
    at Generator.next (<anonymous>)
    at fulfilled (index.ts:1:1)
```

**Comment by terapoon** [comment]
これも修正されました。
